---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-rsyslog
      vars:
        rsyslog_traditional_file_format: false
        rsyslog_omit_local_logging: false
